### ISSUE TITLE
Could this script be improved to support IPv6?

### ISSUE THREAD

**Issue by SiuTo** [philplckthun/setup-simple-ipsec-l2tp-vpn#12] opened 2015-04-02 04:37 UTC
I have setuped a VPN server successfully! Thanks a lot!

But there is two problems when I use this script to setup a L2TP/IPsec server on DigitalOcean:

1. The value of the variable PUBLICIP is an IPv6 address.
2. The VPN server doesn't work until I modify the indent of /etc/ipsec.conf to 8 spaces.

Maybe you could fix these problems. Besides, could you help to improve this script to support IPv6?

**Comment by wolololo** [comment] 2015-04-02 11:04
@SiuTo 

https://www.digitalocean.com/community/questions/nat-gateway-on-digital-ocean-s-droplet-possible

**Comment by theroyalstudent** [comment] 2015-06-15 16:19
@SiuTo Not sure if it's what you wanted, in my newest pull request I've added an option for either IPv4/IPv6 address... Previously PUBLICIP was an IPv6 address for me too, but now I can make it an IPv4 address instead.

**Comment by philplckthun** [comment] 2015-06-15 16:22
The first issue you're addressing is fixed in #25.
The second issue is plainly not an issue. That isn't and has never caused any problems.
The new version of the script is adapted to use the server's IPv6 address and uses IPv4 for the internal communication / the xl2tpd connection, thus the issue is resolved

**Closed by philplckthun** 2015-06-15 16:22 UTC
